---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: midarr
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: midarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        SETUP_ADMIN_EMAIL: "{{ .SETUP_ADMIN_EMAIL }}"
        SETUP_ADMIN_NAME: "{{ .SETUP_ADMIN_NAME }}"
        SETUP_ADMIN_PASSWORD: "{{ .SETUP_ADMIN_PASSWORD }}"
        RADARR_API_KEY: "{{ .RADARR__API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR__API_KEY }}"
        DB_HOSTNAME: &dbHost postgres-rw.database.svc.cluster.local
        DB_DATABASE: &dbName midarr
        DB_USERNAME: &dbUser "{{ .DB_USERNAME }}"
        DB_PASSWORD: &dbPass "{{ .DB_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: midarr
    - extract:
        key: cloudnative-pg
    - extract:
        key: radarr
        property: RADARR__API_KEY
    - extract:
        key: sonarr
        property: SONARR__API_KEY
