---
apiVersion: v1
kind: ConfigMap
metadata:
  name: midarr-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: midarr
        group: guarded
        url: 1.1.1.1
        interval: 1m
        dns:
          query-name: midarr.devbu.io
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover
