---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-qbittorrent-vpn
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-pod-gateway
    - name: cluster-apps-rook-ceph-cluster
  path: ./kubernetes/apps/downloads/qbittorrent-vpn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
