---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: omegabrr
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: omegabrr-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: omegabrr-config-tpl
            items:
              - key: config.yaml
  dataFrom:
    - extract:
        key: omegabrr
    - extract:
        key: autobrr
    - extract:
        key: radarr
        property: RADARR__API_KEY
    - extract:
        key: sonarr
        property: SONARR__API_KEY
