---
originRequest:
  http2Origin: true

ingress:
  - hostname: devbu.io
    service: https://nginx-external-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: external.devbu.io
  - hostname: "*.devbu.io"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: external.devbu.io
  - service: http_status:404
