---
apiVersion: v1
kind: ConfigMap
metadata:
  name: libreddit-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: libreddit
        group: external
        url: https://fuckspez.devbu.io/settings
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
