---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lidarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        LIDARR__API_KEY: "{{ .LIDARR__API_KEY }}"
        LIDARR__POSTGRES_HOST: &dbhost postgres-rw.database.svc.cluster.local
        LIDARR__POSTGRES_PORT: "5432"
        LIDARR__POSTGRES_USER: "{{ .LIDARR__POSTGRES_USER }}"
        LIDARR__POSTGRES_PASSWORD: "{{ .LIDARR__POSTGRES_PASSWORD }}"
        LIDARR__POSTGRES_MAIN_DB: lidarr_main
        LIDARR__POSTGRES_LOG_DB: lidarr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: "lidarr_main lidarr_log"
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: "{{ .LIDARR__POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LIDARR__POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: lidarr
    - extract:
        key: cloudnative-pg
