---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: guacamole
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: guacd
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.6
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: guacamole-secret
      02-init-schema:
        image: docker.io/guacamole/guacamole:1.5.0
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: guacamole-secret
        command: ["/bin/sh"]
        args: ["-c", "/opt/guacamole/bin/initdb.sh --postgres > /migrations/init.sql"]
        volumeMounts:
          - { name: migrations, mountPath: /migrations }
      03-init-migrations:
        image: ghcr.io/onedr0p/postgres-initdb:14.6
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: guacamole-secret
        command: ["/bin/bash"]
        args:
          - -c
          - |
            export PGPASSWORD=$(POSTGRES_PASSWORD)
            psql -h $(POSTGRES_HOSTNAME) -d $(POSTGRES_DATABASE) -U $(POSTGRES_USER) -a -w -f /migrations/init.sql || true
        volumeMounts:
          - { name: migrations, mountPath: /migrations }
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: docker.io/guacamole/guacamole
      tag: 1.5.0
    env:
      GUACD_HOSTNAME: guacd.default.svc.cluster.local
      GUACD_PORT: "4822"
    envFrom:
      - secretRef:
          name: guacamole-secret
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "{{ .Release.Name }}.devbu.io"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      migrations:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 250m
        memory: 100Mi
      limits:
        memory: 750Mi
