---
server:
  host: 0.0.0.0
  port: 80
  apiToken: {{ .OMEGABRR_APIKEY }}

schedule: "0 */8 * * *"

clients:
  autobrr:
    host: http://autobrr.default.svc.cluster.local
    apikey: {{ .AUTOBRR_APIKEY }}
  arr:
    - name: radarr
      type: radarr
      host: http://radarr.default.svc.cluster.local
      apikey: {{ .RADARR__API_KEY }}
      filters:
        - 1 # movies

    - name: sonarr
      type: sonarr
      host: http://sonarr.default.svc.cluster.local
      apikey: {{ .SONARR__API_KEY }}
      filters:
        - 2 # shows
      excludeAlternateTitles: true
