---
kubernetes:
  vars:
    ansible_user: devin
    ansible_ssh_port: 22
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.42.10
          ceph_drives:
            - /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S6S1NJ0TB03807K
        k8s-1:
          ansible_host: 192.168.42.11
          ceph_drives:
            - /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S6S1NS0W223961P
        k8s-2:
          ansible_host: 192.168.42.12
          ceph_drives:
            - /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S6S1NS0W224436E
    workers:
      hosts:
        k8s-3:
          ansible_host: 192.168.42.13
          ceph_drives:
            - /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S6S1NS0TC01391F
        k8s-4:
          ansible_host: 192.168.42.14
          ceph_drives:
            - /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S59ANM0W417201H
        k8s-5:
          ansible_host: 192.168.42.15
          ceph_drives:
            - /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S6S1NJ0T813624W
