---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/pkg.crossplane.io/provider_v1.json
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.14.0
